[build]
builder = "nixpacks"
services = ["java"]
command = "mvn -DskipTests clean package"

[variables]
JAVA_VERSION = "17"

[deploy]
start = "java -Dserver.port=$PORT -jar target/ecom-0.0.1-SNAPSHOT.jar"

[secrets]
enabled = false
